# Generated by Django 4.1.4 on 2023-04-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='receipt_load.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailName', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('fiscalDocumentNumber', models.IntegerField()),
                ('fiscalDriveNumber', models.IntegerField()),
                ('fiscalSign', models.IntegerField()),
                ('totalSum', models.FloatField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='receipt_load.retail')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('sum', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipt_load.products')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='receipt_load.store_receipt')),
            ],
        ),
    ]
