# Generated by Django 4.1.4 on 2023-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_load', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retail',
            old_name='address',
            new_name='retailPlace',
        ),
        migrations.AddField(
            model_name='retail',
            name='retailInn',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
