# Generated by Django 4.1.4 on 2023-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_load', '0002_rename_address_retail_retailplace_retail_retailinn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retail',
            name='retailInn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retail',
            name='retailPlace',
            field=models.CharField(max_length=100),
        ),
    ]
