# Generated by Django 4.1.4 on 2023-06-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_load', '0003_alter_purchase_quantity_alter_retail_retailinn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail',
            name='retailPlace',
        ),
    ]
