# Generated by Django 4.1.4 on 2023-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_load', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='keyWords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='categoryVerified',
            field=models.BooleanField(default=False),
        ),
    ]
