# Generated by Django 4.2.4 on 2023-08-03 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0006_product_category_keywords_products_categoryverified"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Product_category",
            new_name="Сategory",
        ),
    ]
