# Generated by Django 4.2.4 on 2023-08-03 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0007_rename_products_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="productName",
            new_name="name",
        ),
    ]
