# Generated by Django 4.2.4 on 2023-08-03 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0008_rename_productname_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categoryVerified",
            new_name="category_verified",
        ),
    ]
