# Generated by Django 4.2.4 on 2023-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0009_rename_categoryverified_product_category_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="sum",
            new_name="total_cost",
        ),
    ]
