# Generated by Django 4.2.4 on 2023-08-03 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0010_rename_sum_purchase_total_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="сategory",
            old_name="categoryName",
            new_name="name",
        ),
    ]
