# Generated by Django 4.2.4 on 2023-08-03 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0013_rename_store_receipt_receipt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="dateTime",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="totalSum",
            new_name="total_cost",
        ),
    ]
