# Generated by Django 4.2.4 on 2023-08-03 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0014_rename_datetime_receipt_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="store",
            new_name="retail",
        ),
    ]
