# Generated by Django 4.2.4 on 2023-08-03 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "receipt_load",
            "0016_rename_fiscaldocumentnumber_receipt_fiscal_document_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="retail",
            old_name="retailInn",
            new_name="inn",
        ),
        migrations.RenameField(
            model_name="retail",
            old_name="retailName",
            new_name="name",
        ),
    ]
