# Generated by Django 4.2.4 on 2023-08-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0017_rename_retailinn_retail_inn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="сategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receipt_load.сategory",
            ),
        ),
    ]
