# Generated by Django 4.2.4 on 2023-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_load", "0019_rename_сategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
