# Generated by Django 4.2.5 on 2023-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_load', '0020_alter_purchase_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='items_count',
            field=models.IntegerField(null=True),
        ),
    ]
